version: '3'
services:
  main:
    build: .
    ports:
     - "8080:8080"

  dashboard:
    build: ./dashboard
    ports:
     - "8081:8081"

  stock:
    build: ./stock
    ports:
     - "8082:8082"


